on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest

      # true for single package
      - name: Echo release_created
        run: echo "${{ steps.release.outputs.release_created }}"

      # true for multiple packages
      - name: Echo releases_created
        run: echo "${{ steps.release.outputs.releases_created }}"
